instance_name = "dev-kh-wb-01"
location      = "us-central1-a"
machine_type  = "n1-standard-1"
boot_disk_type = "PD_SSD"
boot_disk_size_gb = 100
repository = "gcr.io/deeplearning-platform-release/base-cpu"
image_family = "tf-latest-cpu"
no_remove_data_disk = true
no_public_ip = false
no_proxy_access = false
# instance_owners = [ "my@service-account.com"]