name: Python Application CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/src/ichiba/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Move pyproject.toml
      run: cp app/pyproject.toml app/src/ichiba/components/predict/pyproject.toml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: asia-northeast1-docker.pkg.dev/keiba-hacke/ichiba  # リージョンとプロジェクトIDに応じて変更してください
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}  # GitHubのSecretsに設定したサービスアカウントのキー

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: app/src/ichiba/components/predict  # Dockerfileのあるディレクトリを指定します
        dockerfile: app/src/ichiba/components/predict/Dockerfile  # Dockerfileのパスを指定します
        push: true
        tags: asia-northeast1-docker.pkg.dev/keiba-hacke/ichiba/ichibadocker:latest  # プロジェクトID、リポジトリ名、タグに応じて変更してください
        build-args: |
          GCS_BUCKET=dev-kh-gcs-bucket
          GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}