name: Python Application CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: app
        file: app/Dockerfile
        platforms: linux/amd64
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/python312docker:latest

    - name: Run tests
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/python312docker:latest poetry run pytest src tests