name: Python Application CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and test Docker image
      run: |
        cd app
        docker buildx build --platform linux/amd64 -t python312docker .
        docker run --rm python312docker poetry run pytest src tests